#!/usr/bin/python3

# what libraries does this program need?
import getopt, sys, errno, maas_discourse, json
import os.path
from os import path
from pathlib import Path
ENOERR = 0

# how do we print the usage instructions (and exit)?
def usage():
    print("usage: radget -t TOPIC_NUMBER [-a AUTH_FILE]")
    sys.exit(errno.EINVAL)

# what is the main execution flow?
def main():

    # can we successfully get valid program options?
    try:
        opts, args = getopt.getopt(sys.argv[1:], "t:a:")
    except getopt.GetoptError as err:
        print(err)
        sys.exit(errno.EINVAL)

    # how do i know if they didn't type enough options?
    if len(sys.argv) < 3:
        usage()

    # where do i store the option values?
    topic_number = 0
    home = str(Path.home())
    auth_file = home+"/.config/rad/dc.yaml"

    # how do i pull out the options?
    for o, a in opts:
        if o == "-t":
            topic_number = a
        elif o == "-a":
            auth_file = a
        else:
            assert False

    # how do i validate the options?
    # `radget -t TOPIC_NUMBER [-a AUTH_FILE]`
    if topic_number == 0:
        print("radget: invalid topic number:", topic_number)
        usage()

    if not path.exists(auth_file):
        print("radget: no such file or directory:", auth_file)
        usage()

    # make sure we can get the credentials; if not, error output
    credentials = maas_discourse.md_get_credentials(auth_file)
        
    # get the JSON data from the API, with rate limit management
    topic_json = maas_discourse.md_api_get_topic(topic_number, credentials)

    # get the post number from the topic JSON
    post_number = maas_discourse.md_get_post_number( topic_json )
    
    # read the post
    post_json = maas_discourse.md_api_get_post(post_number, credentials)
        
    # extract the article markdown from the json output
    raw = post_json["raw"]

    # write the article markdown to stdout
    sys.stdout.write(raw)


if __name__ == '__main__':
    main()
