#!/usr/bin/python3

# what libraries does this program need?
import getopt, sys, errno, maas_discourse, json
import os.path
from os import path
from pathlib import Path

# how do we print the usage instructions (and exit)?
def usage():
    print("usage: radput -t TOPIC_NUMBER [-a AUTH_FILE]")
    sys.exit(errno.EINVAL)

# what is the main execution flow?
def main():

    # can we successfully get valid program options?
    try:
        opts, args = getopt.getopt(sys.argv[1:], "t:a:")
    except getopt.GetoptError as err:
        print(err)
        sys.exit(errno.EINVAL)

    # how do i know if they didn't type enough options?
    if len(sys.argv) < 3:
        usage()

    # where do i store the option values?
    topic_number = 0
    home = str(Path.home())
    auth_file = home + "/.config/rad/dc.yaml"

    # how do i pull out the options?
    for o, a in opts:
        if o == "-t":
            topic_number = a
        elif o == "-a":
            auth_file = a
        else:
            assert False

    # how do i validate the options?
    if topic_number == 0:
        print("radget: invalid topic number:", topic_number)
        usage()

    if not path.exists(auth_file):
        print("radget: no such file or directory:", auth_file)
        usage()

    # make sure we can get the credentials; if not, error output
    credentials = maas_discourse.md_get_credentials(auth_file)

    # get the markdown from stdin
    markdown = sys.stdin.read()

    # get the JSON data from the API, with rate limit management
    topic_json = maas_discourse.md_api_get_topic(topic_number, credentials)

    # get the post number from the topic JSON
    post_number = maas_discourse.md_get_post_number( topic_json )

    # pad the markdown to 9000 chars to avoid discourse bug
    markdown = markdown.ljust(9000)

    # create a dictionary buffer for the markdown
    data = {}

    # place the markdown in the appropriate json keys
    data["raw"] = markdown
    # write the post
    post_json = maas_discourse.md_api_put_post(post_number, markdown, credentials)
        
    print("^", end="")
    
if __name__ == '__main__':
    main()
