u.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 8/4/10               \" DATE
.Dt rlink 7      \" Program name and manual section number
.Os Ubuntu
.Sh NAME                 \" Section Header - required - don't modify
.Nm rlink
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line.
.\" Use .Nm macro to designate other names for the documented program.
.Nd adjust links in RAD document to match current document selector.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.\".Op Fl abcd              \" [-abcd]
.Op Fl s Ar selector         \" [-a path]
.\".Op Ar file              \" [file]
.\".Op Ar                   \" [file ...]
.\".Ar arg0                 \" Underlined argument - use .Ar anywhere to underline
.\"arg2 ...                 \" Arguments
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
converts all RAD doc links in stdin to point to the correct discourse topic numbers.
.\".Ar underlined text .
.Pp                      \" Inserts a space
.Pp                      \" Inserts a space
RAD (Reader Adaptive Documentation) text contains markup that indicate which blocks of text should be printed and which should be suppressed.  RAD blocks are marked with
.Ar rad-begin
and
.Ar rad-end
placed by themselves on a single line, accompanied by one or more RAD selectors.
.Pp
Selectors must be of the form
.Ar /vsn/interface
(like
.Ar /2.8/UI
for example). This is the first part of the document URL at https://maas.io/docs, so that website can be used as a source of correct selectors.  
.Pp
Any block of text which is enclosed between RAD selectors that match the input selector is also transferred to stdout.  Any blocks enclosed between selectors that do not match are not transferred.  Any block of text that is not enclosed between RAD selectors is automatically transferred to stdout.
.Pp
The RAD block markers are never transferred.
.Pp
RAD also contains links of the form
.Ar /t/<title-slug>/<topic-number>
-- which are meant to link to another document of the correct RAD version.  The MAAS discourse server uses
.Ar <topic-number>
to select the correct link.  In the RAD topology, documents for a given selector (like
.Ar version-2.8
for example) should point at other RAD documents that match the same selector. 
.Pp
For example, if a RAD file
.Ar Network Topology
with selector
.Ar /2.8/ui
refers to another file in the RAD doc set called
.Ar Subnet Configuration,
there will be one copy of
.Ar Subnet Configuration
for each RAD selector.  This link to
.Ar Subnet Configuration
must be adjusted to point to the
.Ar /2.8/ui
version of that file.  This is done by changing the discourse topic number in the embedded link.
.Pp
.Nm
uses the
.Ar RAD database
to find the correct topic number so that it can adjust links in the standard output to point to the correct version of all references.
.Pp
When preparing the RAD document for
.Nm
to correct, the
.Ar <title-slug>
should be used in place of the normal discourse link, with an
.Ar nnnn
added on the end to signify that a correct topic number is wanted.  For example,
.Nm
will correct the link
.Ar /t/about-maas/nnnn
to point to the version of
.Ar About MAAS
that corresponds to the selector passed to
.Nm
on the command line.  Note that the
.Ar nnnn
is four literal "n" characters, not some substituted integer.
.Pp
You can find the correct
.Ar <title-slug>
by looking at the document and using the last subdirectory on the documents URL -- the text after the last "/" slash.  For example, if you want
.Nm
to substitute each RAD version with the correct link for the
.Ar About MAAS
document, you would find any version of the document on the MAAS documentation website, pull off the last subdir of the URL (in this case,
.Ar about-maas
is the appropriate slug), and place
.Ar /t/about-maas/nnnn
in your master document.   
.Pp
Note that
.Nm
will have to be run once for each RAD variant you want to generate.
.Pp
.Nm
outputs the corrected RAD text to stdout.
.Sh FILES          \" Section Header - required - don't modify
.Ar /etc/rad/rad.db
is the RAD database. See rdbload(7) for details on this file.
.Pp
Note that 
.Nm
looks for a local copy of
.Ar rad.db
in the current working directory, before seeking the system database (above), in case you want to use a modified version for special cases.
.Sh ERRORS              \" Document known, unremedied bugs
.Nm
generates
.Ar EINVAL
if the command line arguments are unintelligible, and
.Ar ENOENT
if the database cannot be found at
.Ar /etc/rad/rad.db
nor in the current working directory.
.Sh SEE ALSO           \" Document history if command behaves in a unique manner
rad(7), rmenu(7), rdbload(7)
